# Generated by Django 2.1 on 2019-05-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_remove_realtor_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='id_mvp',
            new_name='is_mvp',
        ),
    ]
